# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: deploy-oggy-wallet

on:
  push:
    branches:
      - 'releases/**'
      - release
  pull_request:
    branches:
      - 'releases/**'
      - release
  workflow_dispatch:

jobs:
  build:
    environment: Production
    runs-on: ubuntu-latest
    name: Build
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK 11
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'corretto'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@417ae3ccd767c252f5661f1ace9f835f9654f2b5 # v3.1.0

      - name: Build with Gradle Wrapper
        run: |
          chmod +x gradlew
          ./gradlew clean build --exclude-task test

  test:
    needs: build
    environment: production
    runs-on: ubuntu-latest
    name: Test Check
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'corretto'
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@417ae3ccd767c252f5661f1ace9f835f9654f2b5 # v3.1.0

      - name: run test
        run: |
          chmod +x gradlew
          ./gradlew test
  docker-image:
    environment: Production
    needs: test
    runs-on: ubuntu-latest
    name: Docker Image

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: set up secret
        run: curl -sSL ${{secret.ENV}} > ${{ github.workspace }}/src/main/resources/env.properties

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          push: true
          tags: htilssu/ewallet-springboot:latest
  deploy:
    name: deploy
    needs: docker-image
    runs-on: self-hosted
    steps:
      - name: pull image
        run: sudo docker pull htilssu/ewallet-springboot:latest

      - name: rm docker container
        run: sudo docker rm -f ewallet || true

      - name: Run container
        run: sudo docker run --name ewallet -d -p 80:8080 htilssu/ewallet-springboot:latest
